const items = [
  {
    name: 'Vara de los Amantes',
    category: 'instrumento',
    rarity: 'común',
    weight: 3,
    price: 0,
    effects: ['defensa'],
    origins: ['élfico'],
    classes: ['mago', 'druida'],
    side_effects: ['regeneración'],
    description:
      'Instrumento de madera repleto de las energías positivas de su portador, si dos varas de los amantes tienen sincronía tendrán un efecto aún mayor al común.',
    stock: 0,
  },
  {
    name: 'Escudo Avasallante',
    category: 'instrumento',
    rarity: 'extraordinario',
    weight: 3,
    price: 0,
    effects: ['defensa'],
    origins: ['demoníaco'],
    classes: ['paladín', 'bárbaro', 'alquimista'],
    side_effects: ['tensión'],
    description:
      'Escudos invocados por magos oscuros para su venta en este plano.',
    stock: 0,
  },
  {
    name: 'Daga Impía',
    category: 'instrumento',
    rarity: 'raro',
    weight: 1,
    price: 0,
    effects: ['daño'],
    origins: ['demoníaco'],
    classes: ['paladín'],
    side_effects: ['veneno'],
    description:
      'Armas encontradas a la entrada de distintos pozos de lava conocidos como “Puertas al infierno”.',
    stock: 0,
  },
  {
    name: 'Arco Montés',
    category: 'instrumento',
    rarity: 'raro',
    weight: 2,
    price: 0,
    effects: ['daño'],
    origins: ['élfico'],
    classes: ['bárbaro', 'druida', 'paladín'],
    side_effects: [],
    description:
      'Arco creado de madera de roble montañes diseñado para disparar flechas de manera veloz y silenciosa.',
    stock: 0,
  },
  {
    name: 'Imbuidor de Pociones',
    category: 'artefacto',
    weight: 2,
    price: 0,
    effects: ['mejora'],
    origins: ['enano'],
    classes: ['alquimista', 'mago', 'druida'],
    side_effects: [],
    description:
      'Herramienta que permite imbuir tus pociones y transferir sus efectos a distintos instrumentos.',
    rarity: 'extraordinario',
    stock: 0,
  },
  {
    name: 'Poción de Invensibilidad',
    category: 'poción',
    weight: 1,
    price: 0,
    effects: ['mejora'],
    origins: ['doraphim'],
    classes: [],
    side_effects: [],
    description:
      'Brebaje místico difícil de conseguir, concede invencibilidad al daño directo durante dos turnos.',
    rarity: 'extraordinario',
    stock: 0,
  },
  {
    name: 'Poción Vigorizante Ligera',
    category: 'poción',
    weight: 1,
    price: 0,
    effects: ['mejora'],
    origins: ['humano', 'élfico'],
    classes: [],
    side_effects: ['regeneración'],
    description:
      'Brebaje que mejora levemente los atributos de fuerza y destreza del usuario.',
    rarity: 'común',
    stock: 0,
  },
  {
    name: 'Poción Vigorizante Pesada',
    category: 'poción',
    weight: 3,
    price: 0,
    effects: ['mejora'],
    origins: ['humano', 'élfico'],
    classes: [],
    side_effects: ['regeneración'],
    description:
      'Brebaje que mejora medianamente los atributos de fuerza y destreza del usuario.',
    rarity: 'raro',
    stock: 0,
  },
  {
    name: 'Poción Enervante Pesada',
    category: 'poción',
    weight: 3,
    price: 0,
    effects: ['debilitamiento'],
    origins: ['humano', 'élfico'],
    classes: [],
    side_effects: [],
    description: 'Brebaje que baja medianamente las defensas del usuario.',
    rarity: 'raro',
    stock: 0,
  },
  {
    name: 'Poción Enervante Ligera',
    category: 'poción',
    weight: 1,
    rarity: 'común',
    effects: ['debilitamiento'],
    origins: ['humano', 'élfico'],
    classes: [],
    side_effects: [],
    description: 'Brebaje que baja levemente las defensas del usuario.',
    price: 0,
    stock: 0,
  },
  {
    name: 'Poción de Salud Pesada',
    category: 'poción',
    weight: 3,
    rarity: 'raro',
    effects: ['curación'],
    origins: ['humano', 'élfico'],
    classes: [],
    side_effects: ['regeneración'],
    description:
      'Brebaje en gran cantidad que recupera los puntos de vida de manera mediana y da el efecto de regeneración por 3 turnos.',
    price: 0,
    stock: 0,
  },
  {
    name: 'Poción de Salud Ligera',
    category: 'poción',
    weight: 1,
    rarity: 'común',
    effects: ['curación'],
    origins: ['humano', 'élfico'],
    classes: [],
    side_effects: [],
    description: 'Brebaje que recupera de manera leve los puntos de vida.',
    price: 0,
    stock: 0,
  },
  {
    name: 'Olla de Cocción Instantánea',
    category: 'artefacto',
    weight: 2,
    rarity: 'común',
    effects: ['curación'],
    origins: ['humano'],
    classes: [],
    side_effects: ['quemadura'],
    description:
      'Herramienta de cocina portátil y de efecto casi inmediato, los productos cocinados en ella tendrán un efecto levemente mayor de curación (advertencia, evite entrar en contacto con la olla antes de que esta terminé de cocinar).',
    price: 0,
    stock: 0,
  },
  {
    name: 'Orbe de Atracción',
    category: 'artefacto',
    weight: 1,
    rarity: 'raro',
    effects: ['daño'],
    origins: ['élfico'],
    classes: ['mago', 'druida', 'alquimista'],
    side_effects: ['tensión'],
    description:
      'Objeto de un uso que atrae y daña a los enemigos dentro del radio del punto al que fue lanzado.',
    price: 0,
    stock: 0,
  },
  {
    name: 'Espada Fantasma',
    category: 'instrumento',
    weight: 2,
    rarity: 'legendario',
    effects: ['daño'],
    origins: ['humano'],
    classes: ['paladín', 'bárbaro'],
    side_effects: ['congelamiento'],
    description:
      'Espada físicamente frágil con un increíble poder mágico, se dice que quién lo usa puede escuchar los lamentos y consejos de sus anteriores usuarios.',
    price: 0,
    stock: 0,
  },
  {
    name: 'Báculo de las Desgracias',
    category: 'instrumento',
    weight: 3,
    rarity: 'legendario',
    effects: ['debilitamiento'],
    origins: ['demoníaco'],
    classes: [],
    side_effects: ['veneno', 'quemadura', 'tensión', 'congelamiento'],
    description:
      'Cetro de madera oscura e inquebrantable capaz de lanzar cualquier maldición habida y por haber, el uso constante de esta arma puede drenar de su fuerza vital al portador. Se dice que la calamidad llega tras de quién sea que la use.',
    price: 0,
    stock: 0,
  },
  {
    name: 'Justicia Divina',
    category: 'instrumento',
    weight: 2,
    rarity: 'legendario',
    effects: ['daño', 'curación', 'debilitamiento', 'defensa', 'mejora'],
    origins: ['doraphim'],
    classes: [],
    side_effects: ['regeneración', 'quemadura', 'tensión', 'congelamiento'],
    description:
      'Arma de aspecto cambiante y adaptable capaz de liberar de cualquier maldición a su usuario, conocida por su amplia cantidad de hechizos y protecciones. Se dice que forma un vínculo con su usuario hasta que este muere.',
    price: 0,
    stock: 0,
  },
  {
    name: 'Alta Defensa',
    category: 'pergamino',
    weight: 1,
    rarity: 'extraordinario',
    effects: ['defensa'],
    origins: ['enano'],
    classes: ['mago', 'bárbaro', 'druida'],
    side_effects: ['tensión'],
    description:
      'Pergamino de aprendizaje: encantamiento para mejorar la resistencia al daño y dolor de un usuario.',
    price: 0,
    stock: 0,
  },
  {
    name: 'Espíritu Bestia',
    category: 'pergamino',
    weight: 1,
    rarity: 'extraordinario',
    effects: ['daño'],
    origins: ['élfico'],
    classes: ['mago', 'bárbaro', 'druida'],
    side_effects: [],
    description:
      'Pergamino de un solo uso: hechizo de invocación para el espíritu de una bestia enorme y de gran poder, daña por zona a los enemigos por 2 turnos.',
    price: 0,
    stock: 0,
  },
  {
    name: 'Círculo Divino',
    category: 'pergamino',
    weight: 1,
    rarity: 'extraordinario',
    effects: ['curación'],
    origins: ['doraphim'],
    classes: ['mago', 'bárbaro', 'druida'],
    side_effects: [],
    description:
      'Pergamino de un solo uso: hechizo de curación de área, sana a los usuarios elegidos hasta que hayan recuperado el equivalente a la mitad de sus vidas.',
    price: 0,
    stock: 0,
  },
];

export default items;
