import 'dotenv/config';

const {
  PORT,
  NODE_ENV,
  ADMIN_ID,
  ADMIN_EMAIL,
  MONGODB_URI,
  clientDB,
  NODEMAILER_ACCOUNT,
  JWT_SECRET,
  JWT_TOKEN_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_VERIFY_SERVICE_SID,
} = process.env;

const config = {
  PORT,
  NODE_ENV,
  ADMIN_ID,
  ADMIN_EMAIL,
  MONGODB_URI,
  clientDB,
  NODEMAILER_ACCOUNT,
  JWT_SECRET,
  JWT_TOKEN_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_VERIFY_SERVICE_SID,
};

export default config;
